spring:
  application:
    name: checkers-api
  datasource:
    url: jdbc:postgresql://${DB_IP}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: ${PORT:8080}
