version: '3'

networks:
  iataaa:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24

services:
  checkers-api-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: iataaa
      MYSQL_USER: iataaa
      MYSQL_PASSWORD: password
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      iataaa:
        ipv4_address: 172.16.0.15

  checkers-api:
    build: checkers-api
    environment:
      DB_IP: 172.16.0.15
      DB_PORT: 3306
      DB_DATABASE: iataaa
      DB_USER: iataaa
      DB_PASSWORD: password
      VERSION: 0.1.0
    depends_on:
      - checkers-api-db
    networks:
      iataaa:
        ipv4_address: 172.16.0.10

  checkers-rules-api:
    build: checkers-rules-api
    environment:
      VERSION: 0.1.0
    networks:
      iataaa:
        ipv4_address: 172.16.0.20