version: '3'

networks:
  iataaa:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24

services:
  checkers-api:
    container_name: checkers-api
    build: checkers/checkers-api
    environment:
      DB_IP: 172.16.0.15
      DB_PORT: 3306
      DB_DATABASE: iataaa
      DB_USER: iataaa
      DB_PASSWORD: password
      VERSION: 0.1.0
    depends_on:
      - checkers-api-db
    networks:
      iataaa:
        ipv4_address: 172.16.0.10

  checkers-api-db:
    container_name: checkers-api-db
    image: postgres
    environment:
      POSTGRES_ROOT_PASSWORD: password
      POSTGRES_DB: iataaa
      POSTGRES_USER: iataaa
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgres:/var/lib/postgres
    networks:
      iataaa:
        ipv4_address: 172.16.0.15

  checkers-rules-api:
    container_name: checkers-rules-api
    build: checkers/checkers-rules-api
    environment:
      VERSION: 0.1.0
    networks:
      iataaa:
        ipv4_address: 172.16.0.20
